[package]
name = "sensors"
version = "0.0.3"
authors = ["nyantec GmbH <dev@nyantec.com>"]
license = "MirOS"
build = "build.rs"
description = "A Rust-friendly interface to lm-sensors"

[dependencies]
libsensors-sys = "0.1.0"
libc = "0.2.30"
