[package]
name = "sensors"
version = "0.0.1"
authors = ["Mikael Voss <mvs@nyantec.com>"]
license = "LGPL-3.0"
build = "build.rs"

[dependencies]
libsensors-sys = { git = "https://github.com/nyantec/libsensors-sys"}
libc = "*"
