[package]
name = "sensors"
version = "0.0.1"
authors = ["nyantec GmbH <dev@nyantec.com>"]
license = "MirOS"
build = "build.rs"
description = "A Rust freindly interface to libsensors-sys"

[dependencies]
libsensors-sys = "*"
libc = "*"
